# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_mainwindow.ui'
#
# Created: Tue Oct 13 23:49:59 2009
#      by: PyQt4 UI code generator 4.5.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        MainWindow.setMinimumSize(QtCore.QSize(640, 480))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Cat.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setMargin(4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setSpacing(2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.viewAllButton = QtGui.QToolButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.viewAllButton.sizePolicy().hasHeightForWidth())
        self.viewAllButton.setSizePolicy(sizePolicy)
        self.viewAllButton.setMinimumSize(QtCore.QSize(70, 0))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Globe.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.viewAllButton.setIcon(icon1)
        self.viewAllButton.setIconSize(QtCore.QSize(32, 32))
        self.viewAllButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.viewAllButton.setObjectName("viewAllButton")
        self.horizontalLayout_3.addWidget(self.viewAllButton)
        self.resetViewButton = QtGui.QToolButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resetViewButton.sizePolicy().hasHeightForWidth())
        self.resetViewButton.setSizePolicy(sizePolicy)
        self.resetViewButton.setMinimumSize(QtCore.QSize(70, 0))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/preview.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.resetViewButton.setIcon(icon2)
        self.resetViewButton.setIconSize(QtCore.QSize(32, 32))
        self.resetViewButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.resetViewButton.setObjectName("resetViewButton")
        self.horizontalLayout_3.addWidget(self.resetViewButton)
        self.selectAllButton = QtGui.QToolButton(self.centralwidget)
        self.selectAllButton.setMinimumSize(QtCore.QSize(70, 0))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Selection.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.selectAllButton.setIcon(icon3)
        self.selectAllButton.setIconSize(QtCore.QSize(32, 32))
        self.selectAllButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.selectAllButton.setObjectName("selectAllButton")
        self.horizontalLayout_3.addWidget(self.selectAllButton)
        self.helpButton = QtGui.QToolButton(self.centralwidget)
        self.helpButton.setMinimumSize(QtCore.QSize(50, 0))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/Help.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.helpButton.setIcon(icon4)
        self.helpButton.setIconSize(QtCore.QSize(32, 32))
        self.helpButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.helpButton.setObjectName("helpButton")
        self.horizontalLayout_3.addWidget(self.helpButton)
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_3.addWidget(self.line)
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setMinimumSize(QtCore.QSize(48, 48))
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.sizeSlider = QtGui.QSlider(self.centralwidget)
        self.sizeSlider.setMinimum(1)
        self.sizeSlider.setMaximum(20)
        self.sizeSlider.setProperty("value", QtCore.QVariant(5))
        self.sizeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.sizeSlider.setTickPosition(QtGui.QSlider.TicksAbove)
        self.sizeSlider.setTickInterval(1)
        self.sizeSlider.setObjectName("sizeSlider")
        self.horizontalLayout_3.addWidget(self.sizeSlider)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setSpacing(10)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setMinimumSize(QtCore.QSize(32, 32))
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(2, -1, 2, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.zoomSlider = QtGui.QSlider(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zoomSlider.sizePolicy().hasHeightForWidth())
        self.zoomSlider.setSizePolicy(sizePolicy)
        self.zoomSlider.setMinimum(1)
        self.zoomSlider.setMaximum(179)
        self.zoomSlider.setSliderPosition(45)
        self.zoomSlider.setOrientation(QtCore.Qt.Vertical)
        self.zoomSlider.setInvertedAppearance(True)
        self.zoomSlider.setObjectName("zoomSlider")
        self.horizontalLayout_2.addWidget(self.zoomSlider)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4.addLayout(self.verticalLayout_4)
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtGui.QHBoxLayout(self.frame)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = GlWidget(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setFocusPolicy(QtCore.Qt.NoFocus)
        self.widget.setObjectName("widget")
        self.horizontalLayout.addWidget(self.widget)
        self.horizontalLayout_4.addWidget(self.frame)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.verticalLayout.addLayout(self.verticalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.actionQuit = QtGui.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/Delete.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionQuit.setIcon(icon5)
        self.actionQuit.setObjectName("actionQuit")
        self.actionHelp = QtGui.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/Help.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionHelp.setIcon(icon6)
        self.actionHelp.setObjectName("actionHelp")
        self.actionAbout = QtGui.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/Information.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout.setIcon(icon7)
        self.actionAbout.setObjectName("actionAbout")
        self.menuFile.addAction(self.actionQuit)
        self.menuHelp.addAction(self.actionHelp)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.resetViewButton, QtCore.SIGNAL("clicked()"), self.widget.resetView)
        QtCore.QObject.connect(self.viewAllButton, QtCore.SIGNAL("clicked()"), self.widget.viewAll)
        QtCore.QObject.connect(self.selectAllButton, QtCore.SIGNAL("clicked()"), self.widget.selectAll)
        QtCore.QObject.connect(self.helpButton, QtCore.SIGNAL("clicked()"), self.widget.showHelpEvent)
        QtCore.QObject.connect(self.zoomSlider, QtCore.SIGNAL("valueChanged(int)"), self.widget.zoomSliderChangeEvent)
        QtCore.QObject.connect(self.sizeSlider, QtCore.SIGNAL("valueChanged(int)"), self.widget.sizeSliderChangeEvent)
        QtCore.QObject.connect(self.actionAbout, QtCore.SIGNAL("triggered()"), self.widget.showAboutEvent)
        QtCore.QObject.connect(self.actionHelp, QtCore.SIGNAL("triggered()"), self.widget.showHelpEvent)
        QtCore.QObject.connect(self.actionQuit, QtCore.SIGNAL("triggered()"), self.widget.quitEvent)
        QtCore.QObject.connect(self.sizeSlider, QtCore.SIGNAL("sliderPressed()"), self.widget.sizeSliderPressedEvent)
        QtCore.QObject.connect(self.sizeSlider, QtCore.SIGNAL("sliderReleased()"), self.widget.sizeSliderReleasedEvent)
        QtCore.QObject.connect(self.zoomSlider, QtCore.SIGNAL("sliderPressed()"), self.widget.zoomSliderPressedEvent)
        QtCore.QObject.connect(self.zoomSlider, QtCore.SIGNAL("sliderReleased()"), self.widget.zoomSliderReleasedEvent)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Joaquim", None, QtGui.QApplication.UnicodeUTF8))
        self.viewAllButton.setText(QtGui.QApplication.translate("MainWindow", "View All", None, QtGui.QApplication.UnicodeUTF8))
        self.resetViewButton.setText(QtGui.QApplication.translate("MainWindow", "Reset View", None, QtGui.QApplication.UnicodeUTF8))
        self.selectAllButton.setText(QtGui.QApplication.translate("MainWindow", "Select All", None, QtGui.QApplication.UnicodeUTF8))
        self.helpButton.setText(QtGui.QApplication.translate("MainWindow", "Help!", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/resize.png\" /></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/Search.png\" /></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("MainWindow", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHelp.setText(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHelp.setShortcut(QtGui.QApplication.translate("MainWindow", "F1", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))

from glwidget import GlWidget
import images_rc
