from PyQt4 import Qt, QtCore, QtGui
import images_rc

class Ui_Dialog(object):
	"""
	This class represents the about dialog.
	Adapcted from the code generated by QtDesigner.
	"""
	
	def setupUi(self, Dialog):
		"""
		Defines the layout and widgets of the interface.
		"""
		
		Dialog.setObjectName("Dialog")
		Dialog.resize(458, 289)
		icon = QtGui.QIcon()
		icon.addPixmap(QtGui.QPixmap(":/Information.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		Dialog.setWindowIcon(icon)
		
		self.verticalLayout_2 = QtGui.QVBoxLayout(Dialog)
		self.verticalLayout_2.setObjectName("verticalLayout_2")
		self.verticalLayout = QtGui.QVBoxLayout()
		self.verticalLayout.setObjectName("verticalLayout")
		
		self.widget = QtGui.QWidget(Dialog)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
		self.widget.setSizePolicy(sizePolicy)
		self.widget.setObjectName("widget")
		
		self.label = QtGui.QLabel(self.widget)
		self.label.setGeometry(QtCore.QRect(20, 0, 391, 271))
		self.label.setObjectName("label")
		
		self.pushButton = QtGui.QPushButton(self.widget)
		self.pushButton.setGeometry(QtCore.QRect(360, 240, 75, 23))
		self.pushButton.setObjectName("pushButton")
		self.verticalLayout.addWidget(self.widget)
		self.verticalLayout_2.addLayout(self.verticalLayout)

		self.retranslateUi(Dialog)
		
		QtCore.QObject.connect(self.pushButton, QtCore.SIGNAL("clicked()"), Dialog.reject)
		
		QtCore.QMetaObject.connectSlotsByName(Dialog)

	def retranslateUi(self, Dialog):
		"""
		Defines the titles and texts.
		"""
		
		Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "About Joaquim", None,
														   QtGui.QApplication.UnicodeUTF8))
		self.label.setText(QtGui.QApplication.translate("Dialog","<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/Joaquim.png\" /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt; font-weight:600; color:#00007f;\">Joaquim</span><span style=\" font-size:9pt; color:#00007f;\"> is a project that allows a first look at computer</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt; color:#00007f;\">graphics. The user can interact with cubes and spheres in</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt; color:#00007f;\">an easy and simple interface.</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:9pt; color:#00007f;\"></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt; color:#00007f;\">Developers:</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt; font-style:italic; color:#00007f;\">   Fernando Seabra Chirigati</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt; font-style:italic; color:#00007f;\">   Rafael Shinji Aoki Kikuchi</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt; font-style:italic; color:#00007f;\">   Renan Ribeiro de Vasconcelos</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
		self.pushButton.setText(QtGui.QApplication.translate("Dialog", "Ok", None, QtGui.QApplication.UnicodeUTF8))