from PyQt4 import Qt, QtCore, QtGui

from glwidget import GlWidget
from about_dialog import *
from help_dialog import *
import images_rc

class Ui_MainWindow(object):
	"""
	Interface for the main window.
	Adapcted from the code generated by QtDesigner.
	"""
	
	def setupUi(self, MainWindow):
		"""
		Defines the layout and widgets of the interface.
		"""
		
		MainWindow.setObjectName("MainWindow")
		MainWindow.resize(641, 474)
		icon = QtGui.QIcon()
		icon.addPixmap(QtGui.QPixmap(":/Cat.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		MainWindow.setWindowIcon(icon)
		
		self.centralwidget = QtGui.QWidget(MainWindow)
		self.centralwidget.setObjectName("centralwidget")
		
		self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
		self.verticalLayout.setMargin(4)
		self.verticalLayout.setObjectName("verticalLayout")
		
		self.verticalLayout_3 = QtGui.QVBoxLayout()
		self.verticalLayout_3.setSpacing(2)
		self.verticalLayout_3.setObjectName("verticalLayout_3")
		
		self.horizontalLayout_3 = QtGui.QHBoxLayout()
		self.horizontalLayout_3.setObjectName("horizontalLayout_3")
		
		self.viewAllButton = QtGui.QToolButton(self.centralwidget)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.viewAllButton.sizePolicy().hasHeightForWidth())
		self.viewAllButton.setSizePolicy(sizePolicy)
		self.viewAllButton.setMinimumSize(QtCore.QSize(64, 0))
		icon = QtGui.QIcon()
		icon.addPixmap(QtGui.QPixmap(":/Globe.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.viewAllButton.setIcon(icon)
		self.viewAllButton.setIconSize(QtCore.QSize(32, 32))
		self.viewAllButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
		self.viewAllButton.setObjectName("viewAllButton")
		self.horizontalLayout_3.addWidget(self.viewAllButton)
		
		self.resetViewButton = QtGui.QToolButton(self.centralwidget)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.resetViewButton.sizePolicy().hasHeightForWidth())
		self.resetViewButton.setSizePolicy(sizePolicy)
		self.resetViewButton.setMinimumSize(QtCore.QSize(64, 0))
		icon1 = QtGui.QIcon()
		icon1.addPixmap(QtGui.QPixmap(":/Picture.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.resetViewButton.setIcon(icon1)
		self.resetViewButton.setIconSize(QtCore.QSize(32, 32))
		self.resetViewButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
		self.resetViewButton.setObjectName("resetViewButton")
		self.horizontalLayout_3.addWidget(self.resetViewButton)
		
		self.line = QtGui.QFrame(self.centralwidget)
		self.line.setFrameShape(QtGui.QFrame.VLine)
		self.line.setFrameShadow(QtGui.QFrame.Sunken)
		self.line.setObjectName("line")
		self.horizontalLayout_3.addWidget(self.line)
		
		self.label = QtGui.QLabel(self.centralwidget)
		self.label.setObjectName("label")
		self.horizontalLayout_3.addWidget(self.label)
		
		self.sizeSlider = QtGui.QSlider(self.centralwidget)
		self.sizeSlider.setRange(1,20)
		self.sizeSlider.setTickInterval(18)
		self.sizeSlider.setSliderPosition(0.5)
		self.sizeSlider.setProperty("value", QtCore.QVariant(5))
		self.sizeSlider.setOrientation(QtCore.Qt.Horizontal)
		self.sizeSlider.setTickPosition(QtGui.QSlider.TicksAbove)
		self.sizeSlider.setObjectName("sizeSlider")
		self.horizontalLayout_3.addWidget(self.sizeSlider)
		self.verticalLayout_3.addLayout(self.horizontalLayout_3)
		
		self.horizontalLayout_4 = QtGui.QHBoxLayout()
		self.horizontalLayout_4.setObjectName("horizontalLayout_4")
		
		self.verticalLayout_4 = QtGui.QVBoxLayout()
		self.verticalLayout_4.setObjectName("verticalLayout_4")
		
		self.label_2 = QtGui.QLabel(self.centralwidget)
		self.label_2.setObjectName("label_2")
		self.verticalLayout_4.addWidget(self.label_2)
		
		self.zoomSlider = QtGui.QSlider(self.centralwidget)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.zoomSlider.sizePolicy().hasHeightForWidth())
		self.zoomSlider.setSizePolicy(sizePolicy)
		self.zoomSlider.setOrientation(QtCore.Qt.Vertical)
		self.zoomSlider.setObjectName("zoomSlider")
		self.zoomSlider.setTickInterval(356)
		self.zoomSlider.setRange(2,358)
		self.verticalLayout_4.addWidget(self.zoomSlider)
		self.horizontalLayout_4.addLayout(self.verticalLayout_4)
		
		self.line_2 = QtGui.QFrame(self.centralwidget)
		self.line_2.setFrameShape(QtGui.QFrame.VLine)
		self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
		self.line_2.setObjectName("line_2")
		self.horizontalLayout_4.addWidget(self.line_2)
		
		self.widget = GlWidget(MainWindow, self.centralwidget)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
		self.widget.setSizePolicy(sizePolicy)
		self.widget.setFocusPolicy(QtCore.Qt.NoFocus)
		self.widget.setObjectName("widget")
		self.horizontalLayout_4.addWidget(self.widget)
		
		self.sliderPosition = 358 - (self.widget.camera.FOVY*2)
		self.zoomSlider.setSliderPosition(self.sliderPosition)
		
		# Indicates whether the user pressed the zoom slider or not
		self.isPressedZoomSlider = False
		
		# Indicates whether the user pressed the size slider or not
		self.isPressedSizeSlider = False
		
		self.verticalLayout_3.addLayout(self.horizontalLayout_4)
		self.verticalLayout.addLayout(self.verticalLayout_3)
		
		MainWindow.setCentralWidget(self.centralwidget)
		
		self.menubar = QtGui.QMenuBar(MainWindow)
		self.menubar.setGeometry(QtCore.QRect(0, 0, 641, 22))
		self.menubar.setObjectName("menubar")
		self.menuFile = QtGui.QMenu(self.menubar)
		self.menuFile.setObjectName("menuFile")
		self.menuHelp = QtGui.QMenu(self.menubar)
		self.menuHelp.setObjectName("menuHelp")
		
		MainWindow.setMenuBar(self.menubar)
		
		self.actionQuit = QtGui.QAction(MainWindow)
		self.actionQuit.setObjectName("actionQuit")
		iconQuit = QtGui.QIcon()
		iconQuit.addPixmap(QtGui.QPixmap(":/Delete.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.actionQuit.setIcon(iconQuit)
		self.actionHelp = QtGui.QAction(MainWindow)
		self.actionHelp.setObjectName("actionHelp")
		iconHelp = QtGui.QIcon()
		iconHelp.addPixmap(QtGui.QPixmap(":/Help.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.actionHelp.setIcon(iconHelp)
		self.actionAbout = QtGui.QAction(MainWindow)
		self.actionAbout.setObjectName("actionAbout")
		iconAbout = QtGui.QIcon()
		iconAbout.addPixmap(QtGui.QPixmap(":/Information.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.actionAbout.setIcon(iconAbout)
		
		self.menuFile.addAction(self.actionQuit)
		self.menuHelp.addAction(self.actionHelp)
		self.menuHelp.addSeparator()
		self.menuHelp.addAction(self.actionAbout)
		self.menubar.addAction(self.menuFile.menuAction())
		self.menubar.addAction(self.menuHelp.menuAction())

		self.retranslateUi(MainWindow)
		QtCore.QMetaObject.connectSlotsByName(MainWindow)
		
		self.connectSignals()
		
	def connectSignals(self):
		"""
		Map signals between various GUI components.
		"""
		
		QtCore.QObject.connect(self.viewAllButton, Qt.SIGNAL("clicked()"), self.widget.homeKeyPressEvent)
		
		QtCore.QObject.connect(self.resetViewButton, Qt.SIGNAL("clicked()"), self.widget.resetView)
		
		QtCore.QObject.connect(self.zoomSlider, Qt.SIGNAL("sliderPressed()"), self.zoomSliderPressed)
		QtCore.QObject.connect(self.zoomSlider, Qt.SIGNAL("valueChanged(int)"), self.zoomSliderChanged)
		QtCore.QObject.connect(self.zoomSlider, Qt.SIGNAL("sliderReleased()"), self.zoomSliderReleased)
		
		QtCore.QObject.connect(self.sizeSlider, Qt.SIGNAL("sliderPressed()"), self.sizeSliderPressed)
		QtCore.QObject.connect(self.sizeSlider, Qt.SIGNAL("valueChanged(int)"), self.sizeSliderChanged)
		QtCore.QObject.connect(self.sizeSlider, Qt.SIGNAL("sliderReleased()"), self.sizeSliderReleased)
		
		QtCore.QObject.connect(self.actionAbout, Qt.SIGNAL("triggered()"), self.showAboutMessage)
		QtCore.QObject.connect(self.actionHelp, Qt.SIGNAL("triggered()"), self.showHelpMessage)
		
	def zoomSliderPressed(self):
		"""
		Called when the zoom slider is pressed.
		"""
		
		self.isPressedZoomSlider = True
	
	def zoomSliderChanged(self):
		"""
		Called when the zoom slider's value is changed.
		"""
		
		value = self.zoomSlider.value()
		
		if self.isPressedZoomSlider:
			diff = abs(value - self.sliderPosition)
			if value > self.sliderPosition:
				for i in range(diff):
					self.widget.zoomIn()
			elif value < self.sliderPosition:
				for i in range(diff):
					self.widget.zoomOut()
			
		self.sliderPosition = value
		
	def zoomSliderReleased(self):
		"""
		Called when the zoom slider is released.
		"""
		
		self.isPressedZoomSlider = False
		
	def sizeSliderPressed(self):
		"""
		Called when the size slider is pressed.
		"""
		
		self.isPressedSizeSlider = True
		
	def sizeSliderChanged(self):
		"""
		Called when the size slider'value is changed.
		"""
		
		value = self.sizeSlider.value() * 0.1
		if self.isPressedSizeSlider:
			self.widget.changeSelectedObjectsSize(value)
		
	def sizeSliderReleased(self):
		"""
		Called when the size slider is released.
		"""
		
		self.isPressedSizeSlider = False
		
	def setZoomSliderValue(self, value):
		"""
		Sets the value of the zoom slider.
		"""
		
		self.zoomSlider.setValue(value)
		
	def getSizeSliderValue(self):
		"""
		Gets the value of the size slider.
		"""
		
		return self.sizeSlider.value() * 0.1
		
	def setSizeSliderValue(self, value):
		"""
		Sets the value of the size slider.
		"""
		
		if value != 0:
			self.sizeSlider.setValue(value)
			
	def showAboutMessage(self):
		"""
		Shows the about dialog.
		"""
		
		aboutMessage = AboutDialog()
		aboutMessage.exec_()
		
	def showHelpMessage(self):
		"""
		Shows the help dialog.
		"""
		
		aboutMessage = HelpDialog()
		aboutMessage.exec_()

	def retranslateUi(self, MainWindow):
		"""
		Defines the titles and texts.
		"""
		
		MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Joaquim", None,
															   QtGui.QApplication.UnicodeUTF8))
		self.viewAllButton.setText(QtGui.QApplication.translate("MainWindow", "View All", None,
																QtGui.QApplication.UnicodeUTF8))
		self.resetViewButton.setText(QtGui.QApplication.translate("MainWindow", "Reset View", None,
																  QtGui.QApplication.UnicodeUTF8))
		self.label.setText(QtGui.QApplication.translate("MainWindow", "Object Size", None,
														QtGui.QApplication.UnicodeUTF8))
		self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Zoom", None,
														  QtGui.QApplication.UnicodeUTF8))
		self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None,
															QtGui.QApplication.UnicodeUTF8))
		self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None,
															QtGui.QApplication.UnicodeUTF8))
		self.actionQuit.setText(QtGui.QApplication.translate("MainWindow", "Quit", None,
															 QtGui.QApplication.UnicodeUTF8))
		self.actionHelp.setText(QtGui.QApplication.translate("MainWindow", "Help", None,
															 QtGui.QApplication.UnicodeUTF8))
		self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "About", None,
															  QtGui.QApplication.UnicodeUTF8))